config/routes.rb
SampleApp::Application.routes.draw do
 root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
    match '/demo', to: 'static_pages#demo', via: 'get'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

   def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "TypistMonk (BETA)"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
        <div class="row">
          <div class="col-lg-12">
            
            
            <p>Made by <a href="https://github.com/vajradog/">Vajradog</a>.</p>
            <p>Code licensed under the <a href="https://github.com/vajradog/TypistMonk/blob/master/license.txt">The MIT License</a>.</p>
           

          </div>
        </div>
        
      </footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">TypistMonk [beta]</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
           
            
             <li><%= link_to "About this Website", about_path %></li>
           <li>
               <li><%= link_to "More Samples", help_path %></li>
            </li>
            
          </ul>

          <ul class="nav navbar-nav navbar-right">
         <li>
              <a href="https://github.com/vajradog/TypistMonk">Download Source Code</a>
            </li>
          </ul>

        </div>
      </div>
    </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

   <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
          <%= render 'layouts/footer' %>

    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container">

      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-6">
            <h1>About this site</h1>
          </div>
          
        </div>
      </div>

<div class="bs-example">
              <h2>Intention and Warning</h2>
              <p>The intention to create this website is to provide a simple, easy and quick way to edit a sample letter or write your own within the browser and print it with ease, without the need to open a text editor or login to an online service. Basically a 'point-and-shoot' text editor. </p>

              <p>To make it secure and private (and to keep it free), nothing is saved on this website. Once you refresh or close the editor, the session will end and automatically delete whatever was done before.</p>

              <p>Again, the information and services provided here DOES NOT substitute for professional advice. You are using these FREE services of this website at your own risk.</p>
            </div><br/>

<div class="bs-example">
              <h2>For the curious types:</h2>
              <p>I started and built the site with the amazing <a href="http://rubyonrails.org"> Ruby on Rails</a> framework. Eventhough the current site does not use much of what Rails has to offer, however as the Tibetan saying goes,<strong><em>"build the dam before the flood comes",</em> </strong>the decision to use rails was made to facilitate any dynamic feature we may need in the future.</p>

              <p>The text editor is based on <a href="https://github.com/daviferreira">David Ferreira's</a> clone of the beautiful inline editor toolbar <a href="https://medium.com">medium editor</a> and  was written in vanilla Javascript.</p>


              <p>I am not an English major or a lawyer, so I googled sample letters online and edited them slightly.</p>

              <p>The front-end framework is <a href="http://getbootstrap.com">Twitter's bootstrap.</a> This website lives in <a href="http://github.com">Github</a>, runs from <a href="http://heroku.com">Heroku</a> and was made with love by me, Thupten N. Chakrishar.
            </div><br/>

         
  
        </div>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>
<p> Don't contact us yet.</p>

app/views/static_pages/help.html.erb
  <!-- warning line
      ================================================== -->


<div class="container">

      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-12">
            <h1>Resources</h1>
            <p class="lead">Pick recommended links below for professional template, or just <a href="https://www.google.com/#q=sample+letters">Google </a>them. Copy and paste the letter you like in the the blank document provided below.</p>



          </div>
          <div class="col-lg-6">
            
          </div>
        </div>
      </div>

    

            <!-- List Categories
      ================================================== -->
 
    
       
          <!-- warning end
      ================================================== -->



<div class="row">
          <div class="col-lg-4">
            <div class="bs-example">
              <div class="list-group">
                <div class="panel panel-primary">
              <div class="panel-heading">Click Below for:</div>
                 <a href="blank.html" class="list-group-item" target="_blank">Blank Document</a>
              </div>      </div>   </div>
            </div>

          <div class="col-lg-8">
            <div class="bs-example">
              <p>
                <a href="http://jobsearch.about.com/od/JobApplicationLetter/a/job-application-letters.htm" target="_blank"><button type="button" class="btn btn-default" >Application Letters</button></a>
                 <a href="http://jobsearch.about.com/od/coverletters/a/cover-letters-a-z.htm" target="_blank"><button type="button" class="btn btn-primary">Cover Letters</button></a>
                <a href="http://jobsearch.about.com/od/followupletters/Follow_Up_Letters.htm" target="_blank"><button type="button" class="btn btn-success">Folow Up Letters</button></a>
                 <a href="http://jobsearch.about.com/od/jobapplicationletters/Job_Application_Letters.htm" target="_blank"><button type="button" class="btn btn-info">Job Application Letters</button></p>
                <a href="http://jobsearch.about.com/od/referencesrecommendations/a/personal-recommendation-letters.htm" target="_blank"><button type="button" class="btn btn-warning">Personal Recommendation Letters</button>
                <a href="http://jobsearch.about.com/od/employmentrecommendation/a/letters-of-recommendation.htm" target="_blank"><button type="button" class="btn btn-danger">Recommendation Letters for Employment</button>
              </p>
              </div>
             </div>      </div>  </div>


        

app/views/static_pages/home.html.erb
</div>
     </div>
     
<div id="myCarousel" class="carousel">
      <div class="carousel-inner">
        <div class="item active">
<%= image_tag("banner.jpg") %>
          
            </div>
          </div>
        </div>
      </div>
      
    </div><!-- /.carousel -->


<div class="container">
</div></div></div>
  <!-- warning line
      ================================================== -->


<div class="container">

      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-12">
            <h1>In-Browser Editing</h1>
            <p class="lead">Pick a sample letter, edit and print it. No software download, no signup, absolutely free!</p>



          </div>
          <div class="col-lg-6">
            
          </div>
        </div>
      </div>

    

            <!-- List Categories
      ================================================== -->
 
        <div class="row">
          <div class="col-lg-4">
            <div class="bs-example">
              <div class="list-group">
                <div class="panel panel-primary">
              <div class="panel-heading">Employment Related</div>
                <a href="page.html" class="list-group-item" target="_blank">Employer Reference Letter</a>
                <a href="server-resume.html" class="list-group-item" target="_blank">Resume Sample </a>
               <a href="job-inquiry.html" class="list-group-item" target="_blank">Job Inquiry Letter</a>
              </div>      </div>   </div>
            </div>

          <div class="col-lg-4">
            <div class="bs-example">
              <div class="list-group">
                <div class="panel panel-primary">
              <div class="panel-heading">General</div>
             <a href="mail-authorisation.html" class="list-group-item" target="_blank">Authorisation to Collect Mail (on your behalf)</a>
              <a href="iou.html" class="list-group-item" target="_blank">IOU (I Owe You) or Promissory Note </a>
               <a href="notice.html" class="list-group-item" target="_blank">NOTICE (Change to whatever you like)</a>

              </div>
             </div>      </div>  </div>


          <div class="col-lg-4">
            <div class="bs-example">
              <div class="list-group">
                <div class="panel panel-primary">
              <div class="panel-heading">Housing Related</div>
                <a href="landlord-reference.html" class="list-group-item" target="_blank">Landlord Reference Letter</a>
                <a href="rent-lease.html" class="list-group-item" target="_blank">Basic Rental Agreement or Residential Lease</a>
                <a href="apt-for-rent.html" class="list-group-item" target="_blank">Apartment/Room for Rent Ad</a>
              </div>
            </div>
          </div>          </div>   </div>
       

    
       
          <!-- warning end
      ================================================== -->



<div class="row">
          <div class="col-lg-4">
            <div class="bs-example">
              <div class="list-group">
                <div class="panel panel-primary">
              <div class="panel-heading">Certificates</div>
                 <a href="certificate-translation.html" class="list-group-item" target="_blank">Certificate of Translation</a>
              </div>      </div>   </div>
            </div>

          <div class="col-lg-4">
            <div class="bs-example">
              <div class="list-group">
                <div class="panel panel-primary">
              <div class="panel-heading">Affidavits</div>
              <a href="asylum-affidavit.html" class="list-group-item" target="_blank">Affidavit (Asylum Related)</a>
          

              </div>
             </div>      </div>  </div>


          <div class="col-lg-4">
            <div class="bs-example">
              <div class="list-group">
                <div class="panel panel-primary">
              <div class="panel-heading">Blank Document</div>
                 <a href="blank.html" class="list-group-item" target="_blank">Blank Document</a>
              </div>
            </div>
          </div>          </div>   </div>
       
 <!-- warning line
      ================================================== -->

      <div class="container">
         <div class="row">
          <div class="col-lg-12">
            <div class="bs-example">
              <div class="alert alert-dismissable alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4>Warning!</h4>
                 <p>To make it secure and private (and to keep it free), nothing is saved on this website. Once you refresh or close the editor, the session will end and automatically delete whatever was done before.</p>
                <p>THE WEBSITE IS PROVIDED ON AN "AS IS" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT ENDORSE AND ARE NOT RESPONSIBLE FOR THE ACCURACY OR RELIABILITY OF ANY SAMPLE LETTERS, ADVICE OR STATEMENT ON THE WEBSITE. The information provided are no substitute for professional advice.</p>
              </div>
            </div>
          </div>
        </div>